version: "3.9"
services:

  app:
    container_name: n8n
    image: n8nio/n8n:0.236.3
    restart: always
    env_file:
      - .env
    environment:
      N8N_HOST: ${N8N_HOST}
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PASSWORD: redis
    volumes:
      - ./data/app:/home/node/.n8n
      - ./import:/home/node/import
      - ./export:/home/node/export
    ports:
      - "5678:5678"
    depends_on:
      - redis

  api:
    container_name: n8n_api
    image: n8nio/n8n:0.236.3
    restart: always
    env_file:
      - .env
    environment:
      N8N_HOST: ${N8N_API_HOST}
      WEBHOOK_URL: ${API_WEBHOOK_URL}
    volumes:
      - ./data/api:/home/node/.n8n
      - ./import:/home/node/import
      - ./export:/home/node/export
    ports:
      - "5679:5678"

  redis:
    image: redis:6-alpine
    restart: always
    # ports:
    #   - "6379:6379"
    command: redis-server --requirepass redis

  nginx:
    image: nginx:1.25.1-alpine
    command: "/bin/sh -c 'envsubst < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf & while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      NGINX_APP_HOST: lowcode.inovenow.com
      NGINX_APP_API_HOST: lowcode_api.inovenow.com
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - app
      - api

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  n8n_network:
