version: "3.9"
services:

  app:
    container_name: n8n
    image: n8nio/n8n
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.n8n
    ports:
      - "5678:5678"
